# Generated by Django 3.0.5 on 2020-11-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='image',
            field=models.ImageField(upload_to='Album/'),
        ),
    ]
